# Generated by Django 5.0.6 on 2024-05-20 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMesaServicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProcedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipNombre', models.CharField(db_comment='Nombre del tipo de procedimiento', max_length=20, unique=True)),
                ('tipDescripcion', models.TextField(db_comment='Descripcion del tipo de procedimiento', max_length=1000)),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True, db_comment='Fecha y hora del registro')),
                ('fechaHoraActualizacion', models.DateTimeField(auto_now=True, db_comment='Fecha y hora de la ultima actualzacion')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solDescripcion', models.TextField(db_comment='Texto que describe la solicitud del empleado', max_length=1000)),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True, db_comment='fecha y hora del registro')),
                ('fechaHoraActualizacion', models.DateTimeField(auto_now_add=True, db_comment='fecha y hora ultima creacion')),
                ('solOficinaAmbiente', models.ForeignKey(db_comment='hace referencia  a la oficina o ambiente donde se encuentra el equipo de la solicitud', on_delete=django.db.models.deletion.PROTECT, to='appMesaServicio.oficinaambiente')),
                ('solUsuario', models.ForeignKey(db_comment='hace referencia al empleado que hace la solicitud', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casCodigo', models.CharField(db_comment='codigo unico del caso', max_length=10, unique=True)),
                ('casEstado', models.CharField(choices=[('solicitada', 'solicitada'), ('En Proceso', 'En Proceso'), ('Finalizada', 'Finalizada')], max_length=15)),
                ('fechaHoraActualizacion', models.DateTimeField(auto_now_add=True, db_comment='fecha y hora ultima creacion')),
                ('casUsuario', models.ForeignKey(db_comment='empleado de soporte tecnico asignado', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('casoSolicitud', models.ForeignKey(db_comment='hace referencia a la solicitud', on_delete=django.db.models.deletion.PROTECT, to='appMesaServicio.solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='SolucionCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solProcedimiento', models.TextField(db_comment='65', max_length=1000)),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True, db_comment='Fecha y hora del registro')),
                ('fechaHoraActualizacion', models.DateTimeField(auto_now=True, db_comment='Fecha y hora de la ultima actualzacion')),
                ('solCaso', models.ForeignKey(db_comment='hace referencia al caso que genera la solucion del problema', on_delete=django.db.models.deletion.PROTECT, to='appMesaServicio.caso')),
            ],
        ),
        migrations.CreateModel(
            name='SolucionCasoTipoProcedimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solSoluciones', models.ForeignKey(db_comment='hace referencia a la solucion del caso', on_delete=django.db.models.deletion.PROTECT, to='appMesaServicio.solucioncaso')),
                ('solTipoProcedimiento', models.ForeignKey(db_comment='hace referencia a la solucion del caso', on_delete=django.db.models.deletion.PROTECT, to='appMesaServicio.tipoprocedimiento')),
            ],
        ),
    ]
